### ISSUE TITLE
How to use EPEX SPOT SENSOR in an automation?

### ISSUE THREAD

**Issue by WimDeceuninck** [mampfes/ha_epex_spot_sensor#7]
Hi Steffen,

I was able to install EPEX SPOT SENSOR successfully, and the sensor works fine.

But I struggle when using the sensor in a simple automation with a call service switch toggle on/off for a relay.
The relay turns on/off when the sensor 'Enabled' -attribute changes from 'false' to 'true', instead of following the sensor 'Data' -attributes start and end times.

I don't see what I'm doing wrong.
Would you please help me with this?

Below is the information about the sensor and the automations I made.

Thanks in advance for your help.

Kind regards,
Wim

![image](https://github.com/mampfes/ha_epex_spot_sensor/assets/136184765/3ea41d75-0197-41d8-a85b-96cc37970972)

![image](https://github.com/mampfes/ha_epex_spot_sensor/assets/136184765/0ec22bca-cb81-4fbc-a70b-1f9086dbfd81)

![image](https://github.com/mampfes/ha_epex_spot_sensor/assets/136184765/18c997eb-3861-4b68-93af-1315ef10a7f5)

**Comment by mampfes** [comment]
You have to use the state of the sensor, not attribute.

Example (not tested!):

```
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - binary_sensor.my_epex_spot_sensor
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.my_epex_spot_sensor
            state: "on"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.my_switch
            data: {}
      - conditions:
          - condition: state
            entity_id: binary_sensor.my_epex_spot_sensor
            state: "off"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: switch.my_switch
            data: {}
```
